name: Deploy to Amplify on Tag

on:
  push:
    tags:
      - "v*-phoenix-stage"
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: "arn:aws:iam::730335447290:role/github-oidc-provider-aws"
          role-session-name: GithubActions
          role-skip-session-tagging: true
          role-duration-seconds: 1200

      - name: Deploy to Amplify
        run: |
          JOB_ID=$(date +%s) 
          aws amplify start-job \
            --app-id "${{ secrets.AMPLIFY_APP_ID }}" \
            --branch-name master \
            --job-id "$JOB_ID" \
            --job-type RELEASE

