name: Deploy to Amplify on Tag
on:
  push:
    tags:
      - "v*-phoenix"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Deploy to Amplify
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          JOB_ID=$(date +%s) 
          aws amplify start-job \
            --app-id "${{ secrets.AMPLIFY_APP_ID }}" \
            --branch-name master \
            --job-id "$JOB_ID" \
            --job-type RELEASE

#test